### ISSUE TITLE
Add ability to load certs from environment

### ISSUE THREAD

**Issue by keithjeb** [liampauling/gofair#3]
I'm deploying this library on a serverless platform, and as a consequence putting certs/keys on disk is awkward.

Replacing the call to LoadX509KeyPair with X509KeyPair if the key/cert config variables don't look like paths.

**Comment by liampauling** [comment]
Now merged, thanks.

Out of interest how you finding this library? I created it as an excuse to learn some go but haven't touched it since so likely to be a bit buggy.

**Comment by keithjeb** [comment]
It's not yet 'in production' but for the tests I'm doing so far it works well. I'm only using limited features though ( scraping prices every 10 minutes to look for sharbs)
